stages:
  - test
  - build
  - deploy
  - release

before_script:
  - export TERRAFORM_MODULE_SYSTEM=digitalocean

include:
  - component: $CI_SERVER_FQDN/ci/semantic-release/ci-release@~latest
  - template: Terraform-Module.gitlab-ci.yml
